### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 81

### ISSUE THREAD

**Issue by dynect** [ultralytics/google-images-download#3]
When I try to use the script I get the following error:
```
$ python3 bing_scraper.py --url 'https://www.bing.com/images/search?q=flowers' --limit 10 --chromedriver '/Users/Me/Downloads/chromedriver'
Searching for https://www.bing.com/images/search?q=flowers
chromedriver not found (use the '--chromedriver' argument to specify the path to the executable)or google chrome browser is not installed on your machine (exception: Message: session not created: This version of ChromeDriver only supports Chrome version 81
)
$ ls -lat ~/Downloads
-rwxr-xr-x@   1 Me  staff    14786468 Feb 12 19:09 chromedriver
```
Downloaded latest `chromedriver` from [here](https://chromedriver.storage.googleapis.com/81.0.4044.20/chromedriver_mac64.zip).

**Comment by dynect** [comment]
nvm, I had chrome 80 installed, not 81.

**Comment by glenn-jocher** [comment]
It's great to hear that you identified the root cause of the issue. Make sure to update Chrome to version 81 and then the error should be resolved. If you encounter any further issues, feel free to ask for assistance.

**Comment by glenn-jocher** [comment]
No worries! It's great that you figured it out. If you have any more questions or run into any issues, feel free to ask for help. We're always here to assist!

**Comment by glenn-jocher** [comment]
No worries! It happens to the best of us. Feel free to reach out if you encounter any more issues or have any questions. Keep up the great work and happy coding!
